### ISSUE TITLE
IE errors with the latest release

### ISSUE THREAD

**Issue by Wyzix33** [colynb/vanilla.js#3]
I'm getting this error while trying to run my scripts in IE ..
`Line: 0 Column: 0 Error: Script error Code: 0`
Thanks

**Comment by victor-carv** [comment]
According to the [docs](http://colynb.com/vanilla.js/):

> Browser Support
> It's been tested in all modern browsers. With one exception, as of version 1, IE is still not supported. Our team is diligently pursuing not looking into it.
